FROM openjdk:17-alpine as springboot
COPY ./target/bitcoin-timechain-calendar-0.0.1-SNAPSHOT.jar /bitcoin-timechain-calendar-0.0.1-SNAPSHOT.jar
EXPOSE 8080
CMD ["java", "-Xmx1024m", "-jar", "-Dspring.profiles.active=docker", "/bitcoin-timechain-calendar-0.0.1-SNAPSHOT.jar"]
